server:
  port: 8128


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10 ##心跳检测时长
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    instanceInfoReplicationIntervalSeconds: 5
    initialInstanceInfoReplicationIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      
druid:
  url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8
  username: root
  password: root
  useSSL: false
  
mybatis:
  mapperLocations:
    - classpath*:sqlmap/*Mapper.xml
  type-aliases-package: 
     org.springboot.sample.entity

spring:
  zipkin:
    enabled: true
    baseUrl: http://localhost:9411/
  sleuth:
    sampler:
      percentage: 1.0

sample:
  zipkin:
    enabled: true
      
logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: true
      
---
# For deployment in k8s containers      
#spring:
  #profiles: k8s
  #zipkin:
    #enabled: true
    #baseUrl: http://zipkin-server.default.svc.cluster.local:9411/

  #sleuth:
    #sampler:
      #percentage: 0.01
      
         
#logging:
  #level:
    #org.springframework.web.servlet.DispatcherServlet: true
    
#eureka:
  #instance:
    #leaseRenewalIntervalInSeconds: 10
    #prefer-ip-address: true
  #client:
    #region: default
    #registerWithEureka: true
    #fetchRegistry: true
    #useDnsForFetchingServiceUrls: true
    #eurekaServerDNSName: eureka.local
    #eurekaServerPort: 8761
    #eurekaServerURLContext: eureka
    #registryFetchIntervalSeconds: 5
    #instanceInfoReplicationIntervalSeconds: 5
    #initialInstanceInfoReplicationIntervalSeconds: 5
    
    
   